"""Read-operation registry enforcement.

Every outgoing Apple Ads request must match an *enabled* entry in
read_operations.json by exact HTTP method and normalized path. The registry is
generated by scripts/generate_registry.py and human-reviewed; this module only
enforces it. There is no way to register an operation at runtime.

Apple-specific defense (PLAN.md §2.2): the Platform API uses POST for both
reads (``POST /v1/{entity}/query``) and creates (``POST /v1/{entity}``), so
"GET or POST" is not a read signal. The loader therefore refuses any enabled
entry that is not a GET, a POST ending in ``/query``, or the single reviewed
exception ``POST /v1/search/geo`` — and refuses any path carrying a mutating
marker — even if the JSON file was tampered with to say ``enabled``.
"""
from __future__ import annotations

import json
import re
from dataclasses import dataclass
from functools import lru_cache
from importlib import resources

_TEMPLATE_PARAM = re.compile(r"\{[A-Za-z_]+\}")
# Conservative charset for a single path segment (numeric IDs, composite audit
# detail IDs like ``Campaign.123.456``, enum-ish values).
_SEGMENT_RE = r"[A-Za-z0-9_\-.~]+"

READ_POST_EXCEPTIONS = frozenset({"/v1/search/geo"})
MUTATING_MARKERS = ("/apply", "/dismiss", "/bulk-", "/upload")


class OperationDenied(PermissionError):
    """The requested upstream operation is not on the read allowlist."""


@dataclass(frozen=True)
class Operation:
    operation_id: str
    method: str
    path_template: str
    requires_context: str  # "required" | "optional" | "none"
    rate_group: str
    paginated: bool
    sensitivity: str
    _pattern: re.Pattern[str]

    def matches(self, method: str, path: str) -> bool:
        return method.upper() == self.method and bool(self._pattern.fullmatch(path))


def _compile(template: str) -> re.Pattern[str]:
    parts = _TEMPLATE_PARAM.split(template)
    pattern = _SEGMENT_RE.join(re.escape(p) for p in parts)
    return re.compile(pattern)


def is_structurally_read(method: str, path: str) -> bool:
    """The structural read rule, independent of the JSON classification."""
    method = method.upper()
    if any(marker in path for marker in MUTATING_MARKERS):
        return False
    if method == "GET":
        return True
    if method == "POST":
        return path.endswith("/query") or path in READ_POST_EXCEPTIONS
    return False


def _load_raw() -> dict:
    return json.loads(
        resources.files("apple_ads_mcp.policy")
        .joinpath("read_operations.json")
        .read_text()
    )


@lru_cache(maxsize=1)
def load_registry() -> tuple[Operation, ...]:
    raw = _load_raw()
    return _build(raw)


def _build(raw: dict) -> tuple[Operation, ...]:
    ops = []
    for entry in raw["operations"]:
        if entry["classification"] != "enabled":
            continue
        method = entry["method"].upper()
        path = entry["path"]
        # Defense in depth: refuse to load a registry that enables anything
        # outside the structural read rule, even if the file was tampered with.
        if not is_structurally_read(method, path):
            raise OperationDenied(
                f"registry enables a non-read operation: {method} {path}"
            )
        ops.append(
            Operation(
                operation_id=entry["operation_id"],
                method=method,
                path_template=path,
                requires_context=entry.get("requires_context", "required"),
                rate_group=entry.get("rate_group", "entity"),
                paginated=bool(entry.get("paginated")),
                sensitivity=entry.get("sensitivity", "standard"),
                _pattern=_compile(path),
            )
        )
    return tuple(ops)


def normalize_path(path: str) -> str:
    """Normalize a candidate request path before matching.

    Rejects traversal, empty segments, query strings and fragments rather than
    resolving them.
    """
    if "\\" in path or "//" in path or not path.startswith("/"):
        raise OperationDenied(f"malformed request path: {path!r}")
    if "?" in path or "#" in path:
        raise OperationDenied(f"query/fragment not allowed in path: {path!r}")
    segments = path.split("/")
    if any(seg in (".", "..") for seg in segments):
        raise OperationDenied(f"path traversal rejected: {path!r}")
    return path.rstrip("/") or "/"


def authorize(method: str, path: str) -> Operation:
    """Return the matching enabled operation or raise OperationDenied."""
    normalized = normalize_path(path)
    for op in load_registry():
        if op.matches(method, normalized):
            return op
    raise OperationDenied(
        f"operation not on the read allowlist: {method.upper()} {normalized}"
    )
